### ISSUE TITLE
Getting tracebacks

### ISSUE THREAD

**Issue by dkgitdev** [Cap-Cloud/Cap-Elasticsearch-Client#1]
Just opening PyCharm and get following error:

```
Following exceptions happened soon after this one, most probably they are induced.


2021-04-14T13:34:42.024
Access is allowed from event dispatch thread with IW lock only.
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@286acc5d
Current thread: Thread[SE-SearchTask-ActionSearchEverywhereContributor,4,Idea Thread Group] 690455575
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 967636966
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1047)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1022)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3291)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:342)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:198)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:153)
	at com.cap.plugins.elasticsearch.ui.config.a.a.a(Unknown Source)
	at com.cap.plugins.elasticsearch.ui.config.a.a.<init>(Unknown Source)
	at com.cap.plugins.elasticsearch.ui.config.ElasticsearchMainConfigurable.getConfigurables(Unknown Source)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:285)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:71)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:88)
	at com.intellij.openapi.util.NotNullLazyValue$3.compute(NotNullLazyValue.java:80)
	at com.intellij.openapi.util.VolatileNotNullLazyValue.getValue(VolatileNotNullLazyValue.java:19)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:379)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:166)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:116)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:97)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

PyCharm version: 

```

PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
Licensed to Dmitry Akhipenko
Subscription is active until November 1, 2021.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 6
Non-Bundled Plugins: com.cap.plugin.elasticsearch.client (0.3.1), mobi.hsz.idea.gitignore (4.1.0), ir.msdehghan.plugins.ansible (0.92), org.toml.lang (0.2.145.3797-211)

```

**Comment by dkgitdev** [comment]
It appears to happen when plugin cannot connect to the cluster, as its IP is not reachable

**Comment by Cap-Cloud** [comment]
I'm sorry to bring you an unpleasant experience. Will you report the same error when you can connect to the cluster?

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dkgitdev** [comment]
> I'm sorry to bring you an unpleasant experience.

That is completely not a problem. I'm just trying to report :)

> Will you report the same error when you can connect to the cluster?

I do not get this error when successfully connect to the cluster.

**Comment by dkgitdev** [comment]
Ah, I got it while connected

```
Details: Current thread: Thread[SE-SearchTask-ActionSearchEverywhereContributor,4,Idea Thread Group] 402343086
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1621376151

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:38)
	at com.cap.plugins.elasticsearch.ui.config.a.a.<init>(Unknown Source)
	at com.cap.plugins.elasticsearch.ui.config.ElasticsearchMainConfigurable.getConfigurables(Unknown Source)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:285)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:71)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:88)
	at com.intellij.openapi.util.NotNullLazyValue$3.compute(NotNullLazyValue.java:80)
	at com.intellij.openapi.util.VolatileNotNullLazyValue.getValue(VolatileNotNullLazyValue.java:19)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:379)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:166)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:116)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:97)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by Cap-Cloud** [comment]
I have checked some materials. Many projects on GitHub have proposed the same issue, but no suitable solution has been found. Maybe the interface is not compatible with 2021 version. After all, the interface of idea is changing all the time. The place where the plugin throws an exception is to read the configuration file of the favorite API. If you do not configure the favorite API, the configuration file will not exist. I don't know if an error is reported for this reason. You can try adding a favorite API from the settings dialog, even if you don't use it. I will continue to look for solutions, but I don't know how long it will take.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nezda** [comment]
I had to stop using this otherwise awesome plugin because these errors were just too noisy :(
